import type { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";
import { auth } from "@/lib/auth";
import Navbar from "@/components/navbar";
import { ToastContainer } from "react-toastify";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: Readonly<ReactNode>;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <main className="w-full min-h-screen">
          <TooltipProvider>
            <Navbar session={session} />
            <ToastContainer />
            {children}
          </TooltipProvider>
        </main>
      </body>
    </html>
  );
}
